### ISSUE TITLE
init of Mapkit is mot working

### ISSUE THREAD

**Issue by lowfreq2010** [yandex/yandex_maps_mapkit_lite#5]
Hello,

I get the following problem when try to start android app with map_kit_lite

E/flutter (26831): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'yandex_maps_flutter_is_init': undefined symbol: yandex_maps_flutter_is_init
E/flutter (26831): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
E/flutter (26831): #1      _isInit (package:yandex_maps_mapkit_lite/src/bindings/init.dart:15:6)
E/flutter (26831): #2      _isInit (package:yandex_maps_mapkit_lite/src/bindings/init.dart)
E/flutter (26831): #3      initMapkit (package:yandex_maps_mapkit_lite/src/bindings/init.dart:27:7)
E/flutter (26831): #4      main (package:katana/main.dart:22:14)
E/flutter (26831): #5      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter (26831): #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (26831): #7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (26831): 

our code is :

import 'package:yandex_maps_mapkit_lite/init.dart' as init;

void main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  await init.initMapkit(
    apiKey: 'XXX-XXXX-xXXXXXX'
  ); 
}

package has been installed as described on pub.dev page for mapkit_lite

ios app starts just fine. How can we fix this strange problem? Thanks in advance

**Comment by YandexMapKit** [comment]
You need to disable global character stripping.
